version: '3.8'
include:
  - proxy.yaml

services:

  db:
    image: mysql:8
    restart: on-failure
    env_file:
      - .env
    networks:
      backend:
        ipv4_address: 172.20.0.10

  web:
    build:
      dockerfile: Dockerfile.python
    environment:
      - DB_HOST=db
      - DB_USER=app
      - DB_NAME=virtd
      - DB_PASSWORD=QwErTy1234
    restart: on-failure
    networks:
      backend:
        ipv4_address: 172.20.0.5